services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ticket_booking
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "pnpm install &&
             pnpm run dev"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticket_booking
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 